Repository Ostorlab/oxo, pull requests merged in 2025-03, with the labels that each got.

#876 Add record_type to the metadata type
  src/ostorlab/agent/message/proto/v3/report/vulnerability/vulnerability.proto
  src/ostorlab/agent/message/proto/v3/report/vulnerability/vulnerability_pb2.py
  src/ostorlab/agent/mixins/agent_report_vulnerability_mixin.py
Labels: github

#880 feature: Add semantic-pull-request GitHub Action `oxo`
  .github/workflows/lint-pr.yml
Labels: action, fixit!

#883 fix: Update werkzeug dependency
  setup.cfg
Labels: fixit!

#882 fix: Update tenacity dependency.
  setup.cfg
Labels: fixit!
